/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC1 0x01u         /*!<@brief Selects pin function 1 */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name FC0_RXD_SDA_MOSI_DATA (number 93), JP78[2]/P0_29-FC0_RXD_SDA_MOSI_DATA-TRACED2
  @{ */
/* @} */

/*! @name FC0_TXD_SCL_MISO_WS (number 95), JP49[3]/JP80[2]/P0_30-FC0_TXD_SCL_MISO_WS-TRACED1-CAN0_TD
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

#define PIO1_28_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Digital mode: Enable Digital mode. Digital input is enabled. */

/*! @name PIO1_28 (number 72), J122[16]/P1_28
  @{ */

/* Symbols to be used with GPIO driver */
#define MYLEDINIT_LED_RED_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define MYLEDINIT_LED_RED_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */
#define MYLEDINIT_LED_RED_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define MYLEDINIT_LED_RED_PIN 28U                   /*!<@brief PORT pin number */
#define MYLEDINIT_LED_RED_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void MyLEDInit(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Select Digital mode: Enable Digital mode. Digital input is enabled. */
#define PIO1_8_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Mode select (on-chip pull-up/pull-down resistor control): Pull-up. Pull-up resistor enabled. */
#define PIO1_8_MODE_PULL_UP 0x02u

/*! @name PIO1_8 (number 36), J8[1]/P1_8-FC0_CTS-PWM0_A2
  @{ */

/* Symbols to be used with GPIO driver */
#define EMTRIGGERINIT_EMTrig_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define EMTRIGGERINIT_EMTrig_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */
#define EMTRIGGERINIT_EMTrig_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define EMTRIGGERINIT_EMTrig_PIN 8U                   /*!<@brief PORT pin number */
#define EMTRIGGERINIT_EMTrig_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void EMTriggerInit(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
